apiVersion: application.giantswarm.io/v1alpha1
kind: AppCatalogEntry
metadata:
  name: giantswarm-ingress-nginx-3.0.0
  namespace: default
spec:
  appName: ingress-nginx
  appVersion: v1.8.1
  catalog:
    name: giantswarm
    namespace: ""
  chart:
    apiVersion: v1
    home: https://github.com/giantswarm/ingress-nginx-app
    icon: https://s.giantswarm.io/app-icons/ingress-nginx/2/icon_dark.svg
  dateCreated: "2020-09-02T09:40:39Z"
  dateUpdated: "2020-09-02T09:40:39Z"
  restrictions:
    clusterSingleton: true
    compatibleProviders:
    - aws
    fixedNamespace: giantswarm
  version: 3.0.0
